### PR TITLE
@dzucconi Update colors.json

### PR DESCRIPTION
**Pull request by katarinabatina**
color changes...

### CODE REVIEW

**Comment by orta** [comment]
@katarinabatina does `#6e1fff,0.2` represent this colour?

screen shot 2016-03-07 at 12 59 23 pm

**Comment by katarinabatina** [comment]
@orta not the overlap of the two but them independently yes (won't be super relevant for eigen tho as it should only be used for text highlights)

**Comment by katarinabatina** [comment]
image

**Comment by dzucconi** [comment]
I'm going to close this and re-open with some changes to make this work and the appropriate version change.

**Comment by katarinabatina** [comment]
:cry: bye bye first  PR

**Comment by orta** [comment]
Hah, @dzucconi FWIW, transparency is a performance hit on mobile ( re: scrolling mainly ) - so if you're flattening colors :+1:

**Comment by dzucconi** [comment]
Ah, did not think about mobile when I said RGBA would be fine perf-wise. @katarinabatina, can you give us flat hex-values in addition?

**Comment by orta** [comment]
Light purple: `#dcc8ff`
Medium yellow : `#f6d897`
Light yellow: `#feedcc`

**Pull request closed without merging**
